config/routes.rb
Rails.application.routes.draw do
 
 root 'home#index'

  get 'incidents/index'

  resources :detail_vouchers
  resources :vouchers
  resources :employees
  resources :detail_orders
  resources :orders
  resources :reservations
  resources :users
  resources :rooms
  resources :songs
  resources :artists
  resources :products
  resources :events
  resources :locals
  resources :districts
  
  delete 'incidents', controller: :incidents, action: :clear
  

end

app/models/artist.rb
class Artist < ActiveRecord::Base
    
    validates :name, presence: true, 
              uniqueness: {case_sensitive: false}
    

   include Loggable 

end

app/models/detail_order.rb
class DetailOrder < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :song
end

app/models/detail_voucher.rb
class DetailVoucher < ActiveRecord::Base
  belongs_to :voucher
  belongs_to :detail_order
end

app/models/district.rb
class District < ActiveRecord::Base
    has_many :local

    validates :name, presence: true, 
              uniqueness: {case_sensitive: false}
            
    include Loggable  
    
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :local
    
  def local_name    
    self.local.name 
  end
  
  validates :name,  presence: true, 
            uniqueness: {case_sensitive: false}
            
  include Loggable 

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :local
  belongs_to :district
  
  def district_name 
      self.district_name 
  end

  def local_name   
    self.local_name
  end

  validates :name, presence: true, 
          uniqueness: {case_sensitive: false}
            
  include Loggable 
  
end

app/models/incident.rb
class Incident < ActiveRecord::Base
    def self.log(target, messages)
       messages.each do |message|
         Incident.create(target: target, message: message)
       end
    end
    
    def self.clear_log 
        Incident.delete_all 
    end

end

app/models/local.rb
class Local < ActiveRecord::Base
  belongs_to :district
  
    def district_name    
      self.district.name
    end

  validates :name, presence: true, 
            uniqueness: {case_sensitive: false}
            
  include Loggable 

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :local
  belongs_to :room
  belongs_to :user
  
  def local_name    
    self.local.name  
  end

  def room_name    
    self.room.name  
  end

  def user_name    
    self.user.name  
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :local
  
  has_many :detail_orders
  has_many :details_vouchers, through::details_orders 

  def local_name    
    self.local.name  
  end

  validates :name, presence: true, 
            uniqueness: {case_sensitive: false} 
  validates :category, presence: true
  
  include Loggable 

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :local
  belongs_to :event
  belongs_to :room
  belongs_to :user
  
  def local_name    
    self.local.name  
  end

  def event_name    
    self.event.name  
  end

  def room_name    
    self.room.name  
  end

  def user_name    
    self.user.name  
  end

end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :local
  
  def local_name  
    self.local.name
  end

  validates :name, presence: true, 
          uniqueness: {case_sensitive: false}
            
  include Loggable 

end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist
  
  def artist_name    
    self.artist.name  
  end
  
  validates :name, presence: true, 
            uniqueness: {case_sensitive: false}
            
  include Loggable 
end

app/models/user.rb
class User < ActiveRecord::Base
    
    include Loggable 
    
end

app/models/voucher.rb
class Voucher < ActiveRecord::Base
  belongs_to :room
  belongs_to :user
  belongs_to :local
  belongs_to :employee
end

app/controllers/detail_vouchers_controller.rb
class DetailVouchersController < ApplicationController
  before_action :set_detail_voucher, only: [:show, :edit, :update, :destroy]

  # GET /detail_vouchers
  # GET /detail_vouchers.json
  def index
    @detail_vouchers = DetailVoucher.all
  end

  # GET /detail_vouchers/1
  # GET /detail_vouchers/1.json
  def show
  end

  # GET /detail_vouchers/new
  def new
    @detail_voucher = DetailVoucher.new
  end

  # GET /detail_vouchers/1/edit
  def edit
  end

  # POST /detail_vouchers
  # POST /detail_vouchers.json
  def create
    @detail_voucher = DetailVoucher.new(detail_voucher_params)

    respond_to do |format|
      if @detail_voucher.save
        format.html { redirect_to @detail_voucher, notice: 'Detail voucher was successfully created.' }
        format.json { render :show, status: :created, location: @detail_voucher }
      else
        format.html { render :new }
        format.json { render json: @detail_voucher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /detail_vouchers/1
  # PATCH/PUT /detail_vouchers/1.json
  def update
    respond_to do |format|
      if @detail_voucher.update(detail_voucher_params)
        format.html { redirect_to @detail_voucher, notice: 'Detail voucher was successfully updated.' }
        format.json { render :show, status: :ok, location: @detail_voucher }
      else
        format.html { render :edit }
        format.json { render json: @detail_voucher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /detail_vouchers/1
  # DELETE /detail_vouchers/1.json
  def destroy
    @detail_voucher.destroy
    respond_to do |format|
      format.html { redirect_to detail_vouchers_url, notice: 'Detail voucher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detail_voucher
      @detail_voucher = DetailVoucher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def detail_voucher_params
      params.require(:detail_voucher).permit(:voucher_id, :detail_order_id, :cantProd)
    end
end

app/helpers/detail_vouchers_helper.rb
module DetailVouchersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/detail_vouchers/_form.html.erb
<%= simple_form_for @detail_voucher, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :voucher_id %>
  <%= error_span(@detail_voucher[:voucher_id]) %>
  <%= f.input :detail_order_id %>
  <%= error_span(@detail_voucher[:detail_order_id]) %>
  <%= f.input :cantProd %>
  <%= error_span(@detail_voucher[:cantProd]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                detail_vouchers_path, :class => 'btn btn-default' %>
<% end %>

app/views/detail_vouchers/edit.html.erb
<%- model_class = DetailVoucher -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/detail_vouchers/index.html.erb
<%- model_class = DetailVoucher -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:voucher_id) %></th>
      <th><%= model_class.human_attribute_name(:detail_order_id) %></th>
      <th><%= model_class.human_attribute_name(:cantProd) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @detail_vouchers.each do |detail_voucher| %>
      <tr>
        <td><%= link_to detail_voucher.id, detail_voucher_path(detail_voucher) %></td>
        <td><%= detail_voucher.voucher_id %></td>
        <td><%= detail_voucher.detail_order_id %></td>
        <td><%= detail_voucher.cantProd %></td>
        <td><%=l detail_voucher.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_detail_voucher_path(detail_voucher), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      detail_voucher_path(detail_voucher),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_detail_voucher_path,
            :class => 'btn btn-primary' %>

app/views/detail_vouchers/new.html.erb
<%- model_class = DetailVoucher -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/detail_vouchers/show.html.erb
<%- model_class = DetailVoucher -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:voucher_id) %>:</strong></dt>
  <dd><%= @detail_voucher.voucher_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:detail_order_id) %>:</strong></dt>
  <dd><%= @detail_voucher.detail_order_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cantProd) %>:</strong></dt>
  <dd><%= @detail_voucher.cantProd %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              detail_vouchers_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_detail_voucher_path(@detail_voucher), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              detail_voucher_path(@detail_voucher),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>