config/routes.rb
Rails.application.routes.draw do
 
 root 'home#index'

  get 'incidents/index'

  resources :detail_vouchers
  resources :vouchers
  resources :employees
  resources :detail_orders
  resources :orders
  resources :reservations
  resources :users
  resources :rooms
  resources :songs
  resources :artists
  resources :products
  resources :events
  resources :locals
  resources :districts
  
  delete 'incidents', controller: :incidents, action: :clear
  

end

app/models/artist.rb
class Artist < ActiveRecord::Base
    
    validates :name, presence: true, 
              uniqueness: {case_sensitive: false}
    

   include Loggable 

end

app/models/detail_order.rb
class DetailOrder < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :song
end

app/models/district.rb
class District < ActiveRecord::Base
    has_many :local

    validates :name, presence: true, 
              uniqueness: {case_sensitive: false}
            
    include Loggable  
    
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :local
    
  def local_name    
    self.local.name 
  end
  
  validates :name,  presence: true, 
            uniqueness: {case_sensitive: false}
            
  include Loggable 

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :local
  belongs_to :district
  
  def district_name 
      self.district_name 
  end

  def local_name   
    self.local_name
  end

  validates :name, presence: true, 
          uniqueness: {case_sensitive: false}
            
  include Loggable 
  
end

app/models/incident.rb
class Incident < ActiveRecord::Base
    def self.log(target, messages)
       messages.each do |message|
         Incident.create(target: target, message: message)
       end
    end
    
    def self.clear_log 
        Incident.delete_all 
    end

end

app/models/local.rb
class Local < ActiveRecord::Base
  belongs_to :district
  
    def district_name    
      self.district.name
    end

  validates :name, presence: true, 
            uniqueness: {case_sensitive: false}
            
  include Loggable 

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :local
  belongs_to :room
  belongs_to :user
  
  def local_name    
    self.local.name  
  end

  def room_name    
    self.room.name  
  end

  def user_name    
    self.user.name  
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :local
  
  has_many :detail_orders
  has_many :details_vouchers, through::details_orders 

  def local_name    
    self.local.name  
  end

  validates :name, presence: true, 
            uniqueness: {case_sensitive: false} 
  validates :category, presence: true
  
  include Loggable 

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :local
  belongs_to :event
  belongs_to :room
  belongs_to :user
  
  def local_name    
    self.local.name  
  end

  def event_name    
    self.event.name  
  end

  def room_name    
    self.room.name  
  end

  def user_name    
    self.user.name  
  end

end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :local
  
  def local_name  
    self.local.name
  end

  validates :name, presence: true, 
          uniqueness: {case_sensitive: false}
            
  include Loggable 

end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist
  
  def artist_name    
    self.artist.name  
  end
  
  validates :name, presence: true, 
            uniqueness: {case_sensitive: false}
            
  include Loggable 
end

app/models/user.rb
class User < ActiveRecord::Base
    
    include Loggable 
    
end

app/models/voucher.rb
class Voucher < ActiveRecord::Base
  belongs_to :room
  belongs_to :user
  belongs_to :local
  belongs_to :employee
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:nomE, :apEm, :numDni, :direc, :numtef, :fenac, :local_id)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/employees/_form.html.erb
<%= simple_form_for @employee, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :nomE %>
  <%= error_span(@employee[:nomE]) %>
  <%= f.input :apEm %>
  <%= error_span(@employee[:apEm]) %>
  <%= f.input :numDni %>
  <%= error_span(@employee[:numDni]) %>
  <%= f.input :direc %>
  <%= error_span(@employee[:direc]) %>
  <%= f.input :numtef %>
  <%= error_span(@employee[:numtef]) %>
  <%= f.input :fenac %>
  <%= error_span(@employee[:fenac]) %>
  <%= f.association :local %> 
  <%= error_span(@employee [:local]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                employees_path, :class => 'btn btn-default' %>
<% end %>

app/views/employees/edit.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/employees/index.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nomE) %></th>
      <th><%= model_class.human_attribute_name(:apEm) %></th>
      <th><%= model_class.human_attribute_name(:numDni) %></th>
      <th><%= model_class.human_attribute_name(:direc) %></th>
      <th><%= model_class.human_attribute_name(:numtef) %></th>
      <th><%= model_class.human_attribute_name(:fenac) %></th>
      <th><%= model_class.human_attribute_name(:local_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= link_to employee.id, employee_path(employee) %></td>
        <td><%= employee.nomE %></td>
        <td><%= employee.apEm %></td>
        <td><%= employee.numDni %></td>
        <td><%= employee.direc %></td>
        <td><%= employee.numtef %></td>
        <td><%= employee.fenac %></td>
        <td><%= employee.local_name %></td>
        <td><%=l employee.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_employee_path(employee), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      employee_path(employee),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_employee_path,
            :class => 'btn btn-primary' %>

app/views/employees/new.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/employees/show.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nomE) %>:</strong></dt>
  <dd><%= @employee.nomE %></dd>
  <dt><strong><%= model_class.human_attribute_name(:apEm) %>:</strong></dt>
  <dd><%= @employee.apEm %></dd>
  <dt><strong><%= model_class.human_attribute_name(:numDni) %>:</strong></dt>
  <dd><%= @employee.numDni %></dd>
  <dt><strong><%= model_class.human_attribute_name(:direc) %>:</strong></dt>
  <dd><%= @employee.direc %></dd>
  <dt><strong><%= model_class.human_attribute_name(:numtef) %>:</strong></dt>
  <dd><%= @employee.numtef %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fenac) %>:</strong></dt>
  <dd><%= @employee.fenac %></dd>
  <dt><strong><%= model_class.human_attribute_name(:local_id) %>:</strong></dt>
  <dd><%= @employee.local_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              employees_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_employee_path(@employee), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              employee_path(@employee),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>