config/routes.rb
Rails.application.routes.draw do
 
 root 'home#index'

  get 'incidents/index'

  resources :detail_vouchers
  resources :vouchers
  resources :employees
  resources :detail_orders
  resources :orders
  resources :reservations
  resources :users
  resources :rooms
  resources :songs
  resources :artists
  resources :products
  resources :events
  resources :locals
  resources :districts
  
  delete 'incidents', controller: :incidents, action: :clear
  

end

app/models/artist.rb
class Artist < ActiveRecord::Base
    
    validates :name, presence: true, 
              uniqueness: {case_sensitive: false}
    

   include Loggable 

end

app/models/detail_order.rb
class DetailOrder < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :song
end

app/models/detail_voucher.rb
class DetailVoucher < ActiveRecord::Base
  belongs_to :voucher
  belongs_to :detail_order
end

app/models/district.rb
class District < ActiveRecord::Base
    has_many :local

    validates :name, presence: true, 
              uniqueness: {case_sensitive: false}
            
    include Loggable  
    
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :local
    
  def local_name    
    self.local.name 
  end
  
  validates :name,  presence: true, 
            uniqueness: {case_sensitive: false}
            
  include Loggable 

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :local
  belongs_to :district
  
  def district_name 
      self.district_name 
  end

  def local_name   
    self.local_name
  end

  validates :name, presence: true, 
          uniqueness: {case_sensitive: false}
            
  include Loggable 
  
end

app/models/incident.rb
class Incident < ActiveRecord::Base
    def self.log(target, messages)
       messages.each do |message|
         Incident.create(target: target, message: message)
       end
    end
    
    def self.clear_log 
        Incident.delete_all 
    end

end

app/models/local.rb
class Local < ActiveRecord::Base
  belongs_to :district
  
    def district_name    
      self.district.name
    end

  validates :name, presence: true, 
            uniqueness: {case_sensitive: false}
            
  include Loggable 

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :local
  belongs_to :room
  belongs_to :user
  
  def local_name    
    self.local.name  
  end

  def room_name    
    self.room.name  
  end

  def user_name    
    self.user.name  
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :local
  
  has_many :detail_orders
  has_many :details_vouchers, through::details_orders 

  def local_name    
    self.local.name  
  end

  validates :name, presence: true, 
            uniqueness: {case_sensitive: false} 
  validates :category, presence: true
  
  include Loggable 

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :local
  belongs_to :event
  belongs_to :room
  belongs_to :user
  
  def local_name    
    self.local.name  
  end

  def event_name    
    self.event.name  
  end

  def room_name    
    self.room.name  
  end

  def user_name    
    self.user.name  
  end

end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :local
  
  def local_name  
    self.local.name
  end

  validates :name, presence: true, 
          uniqueness: {case_sensitive: false}
            
  include Loggable 

end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist
  
  def artist_name    
    self.artist.name  
  end
  
  validates :name, presence: true, 
            uniqueness: {case_sensitive: false}
            
  include Loggable 
end

app/models/user.rb
class User < ActiveRecord::Base
    
    include Loggable 
    
end

app/models/voucher.rb
class Voucher < ActiveRecord::Base
  belongs_to :room
  belongs_to :user
  belongs_to :local
  belongs_to :employee
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :local_id, :aforoS, :availabilityS)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/rooms/_form.html.erb
<%= simple_form_for @room, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= error_span(@room[:name]) %>
  <%= f.association :local %> 
  <%= error_span(@room [:local]) %>
  <%= f.input :aforoS %>
  <%= error_span(@room[:aforoS]) %>
  <%= f.input :availabilityS %>
  <%= error_span(@room[:availabilityS]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                rooms_path, :class => 'btn btn-default' %>
<% end %>

app/views/rooms/edit.html.erb
<%- model_class = Room -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/rooms/index.html.erb
<%- model_class = Room -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:local_id) %></th>
      <th><%= model_class.human_attribute_name(:aforoS) %></th>
      <th><%= model_class.human_attribute_name(:availabilityS) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= link_to room.id, room_path(room) %></td>
        <td><%= room.name %></td>
        <td><%= room.local_name %></td>
        <td><%= room.aforoS %></td>
        <td><%= room.availabilityS %></td>
        <td><%=l room.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_room_path(room), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      room_path(room),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_room_path,
            :class => 'btn btn-primary' %>

app/views/rooms/new.html.erb
<%- model_class = Room -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/rooms/show.html.erb
<%- model_class = Room -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @room.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:local_id) %>:</strong></dt>
  <dd><%= @room.local_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:aforoS) %>:</strong></dt>
  <dd><%= @room.aforoS %></dd>
  <dt><strong><%= model_class.human_attribute_name(:availabilityS) %>:</strong></dt>
  <dd><%= @room.availabilityS %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              rooms_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_room_path(@room), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              room_path(@room),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>