config/routes.rb
Rails.application.routes.draw do
 
 root 'home#index'

  get 'incidents/index'

  resources :detail_vouchers
  resources :vouchers
  resources :employees
  resources :detail_orders
  resources :orders
  resources :reservations
  resources :users
  resources :rooms
  resources :songs
  resources :artists
  resources :products
  resources :events
  resources :locals
  resources :districts
  
  delete 'incidents', controller: :incidents, action: :clear
  

end

app/models/artist.rb
class Artist < ActiveRecord::Base
    
    validates :name, presence: true, 
              uniqueness: {case_sensitive: false}
    

   include Loggable 

end

app/models/detail_order.rb
class DetailOrder < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :song
end

app/models/district.rb
class District < ActiveRecord::Base
    has_many :local

    validates :name, presence: true, 
              uniqueness: {case_sensitive: false}
            
    include Loggable  
    
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :local
    
  def local_name    
    self.local.name 
  end
  
  validates :name,  presence: true, 
            uniqueness: {case_sensitive: false}
            
  include Loggable 

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :local
  belongs_to :district
  
  def district_name 
      self.district_name 
  end

  def local_name   
    self.local_name
  end

  validates :name, presence: true, 
          uniqueness: {case_sensitive: false}
            
  include Loggable 
  
end

app/models/incident.rb
class Incident < ActiveRecord::Base
    def self.log(target, messages)
       messages.each do |message|
         Incident.create(target: target, message: message)
       end
    end
    
    def self.clear_log 
        Incident.delete_all 
    end

end

app/models/local.rb
class Local < ActiveRecord::Base
  belongs_to :district
  
    def district_name    
      self.district.name
    end

  validates :name, presence: true, 
            uniqueness: {case_sensitive: false}
            
  include Loggable 

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :local
  belongs_to :room
  belongs_to :user
  
  def local_name    
    self.local.name  
  end

  def room_name    
    self.room.name  
  end

  def user_name    
    self.user.name  
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :local
  
  has_many :detail_orders
  has_many :details_vouchers, through::details_orders 

  def local_name    
    self.local.name  
  end

  validates :name, presence: true, 
            uniqueness: {case_sensitive: false} 
  validates :category, presence: true
  
  include Loggable 

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :local
  belongs_to :event
  belongs_to :room
  belongs_to :user
  
  def local_name    
    self.local.name  
  end

  def event_name    
    self.event.name  
  end

  def room_name    
    self.room.name  
  end

  def user_name    
    self.user.name  
  end

end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :local
  
  def local_name  
    self.local.name
  end

  validates :name, presence: true, 
          uniqueness: {case_sensitive: false}
            
  include Loggable 

end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist
  
  def artist_name    
    self.artist.name  
  end
  
  validates :name, presence: true, 
            uniqueness: {case_sensitive: false}
            
  include Loggable 
end

app/models/user.rb
class User < ActiveRecord::Base
    
    include Loggable 
    
end

app/models/voucher.rb
class Voucher < ActiveRecord::Base
  belongs_to :room
  belongs_to :user
  belongs_to :local
  belongs_to :employee
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :stock, :price, :local_id, :availabilityP)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_form.html.erb
<%= simple_form_for @product, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= error_span(@product[:name]) %>
  <%= f.input :stock %>
  <%= error_span(@product[:stock]) %>
  <%= f.input :price %>
  <%= error_span(@product[:price]) %>
  <%= f.association :local %> 
  <%= error_span(@product[:local]) %>
  <%= f.input :availabilityP %>
  <%= error_span(@product[:availabilityP]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                products_path, :class => 'btn btn-default' %>
<% end %>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:stock) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:local_id) %></th>
      <th><%= model_class.human_attribute_name(:availabilityP) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.id, product_path(product) %></td>
        <td><%= product.name %></td>
        <td><%= product.stock %></td>
        <td><%= product.price %></td>
        <td><%= product.local_name %></td>
        <td><%= product.availabilityP %></td>
        <td><%=l product.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_product_path(product), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      product_path(product),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_product_path,
            :class => 'btn btn-primary' %>

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @product.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:stock) %>:</strong></dt>
  <dd><%= @product.stock %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @product.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:local_id) %>:</strong></dt>
  <dd><%= @product.local_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:availabilityP) %>:</strong></dt>
  <dd><%= @product.availabilityP %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              products_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_product_path(@product), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              product_path(@product),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>